### ISSUE TITLE
关于diff中的节点更新

### ISSUE THREAD

**Issue by xuanskyer** [supnate/react-dom-diff#2]
![https://github.com/xuanskyer/public/blob/master/QQ%E6%88%AA%E5%9B%BE20170304180047.png?raw=true](https://github.com/xuanskyer/public/blob/master/QQ%E6%88%AA%E5%9B%BE20170304180047.png?raw=true)

请教如图，这里的B为什么会更新？

**Comment by supnate** [comment]
Virtual DOM 是每次全局“刷新”，updated 表示该节点已经被 diff 操作比较过。

**Comment by xuanskyer** [comment]
@supnate 
哦，意思是这里只是做了diff操作比较。并没有真正更新是吧？

**Comment by supnate** [comment]
嗯，componentDidUpdate 每次 render 完都会调用，无论 virtual dom 是否发生变化。
